#!/usr/bin/env bash
#
# ~/.dotfiles/debian/install

[ -z "$DOTFILESPATH" ] && { echo "Error: ${0} cannot be called directly"; exit 1; }

DOTFILESPATH="${DOTFILESPATH}/debian"

echo "==> Installing Debian dotfiles..."

echo "${PADDING}[none]"
