#!/usr/bin/env bash
#
# ~/.dotfiles/debian/install

[ -z "$DOTFILES_DIR" ] && { echo "Error: ${0} cannot be called directly"; exit 1; }

DOTFILES_DIR="${DOTFILES_DIR}/debian"

echo "==> Installing Debian dotfiles..."

echo "${PADDING}[none]"
