#!/bin/bash

BASEDIR="$HOME/.dotfiles/arch"
LINKCMD="ln -is"

echo "Installing arch dotfiles..."

# Ensure paths
mkdir -p ~/.config/i3
mkdir -p ~/.config/sway
mkdir -p ~/.config/termite

# Symlink dotfiles
${LINKCMD} ${BASEDIR}/.compton.conf ~/
${LINKCMD} ${BASEDIR}/.i3status.conf ~/
${LINKCMD} ${BASEDIR}/.xbindkeysrc ~/.xbindkeysrc
${LINKCMD} ${BASEDIR}/.xinitrc ~/.xinitrc
${LINKCMD} ${BASEDIR}/.Xresources ~/.Xresources

# Symlink config files
${LINKCMD} ${BASEDIR}/i3.conf ~/.config/i3/config
${LINKCMD} ${BASEDIR}/sway.conf ~/.config/sway/config
${LINKCMD} ${BASEDIR}/termite.conf ~/.config/termite/config