#!/usr/bin/env bash
#
# ~/.dotfiles/arch/install
# dotfiles -- Personal dotfile repo
# Author: Blake Jakopovic
# Git:    https://github.com/blakejakopovic/dotfiles

[ -z "$DOTFILES_DIR" ] && { echo "Error: ${0} cannot be called directly"; exit 1; }

DOTFILES_DIR="${DOTFILES_DIR}/arch"

echo "==> Installing arch dotfiles..."

echo "${PADDING}[none]"