#!/usr/bin/env bash
#
# ~/.dotfiles/osx/install
# dotfiles -- Personal dot file repo
# Author: Blake Jakopovic
# Git:    https://github.com/blakejakopovic/dotfiles

DOTFILES_DIR="${DOTFILES_DIR}/osx"

echo "==> Installing osx dotfiles..."

echo "${PADDING}[none]"