#!/usr/bin/env bash
#
# ~/.dotfiles/osx/install
# dotfiles -- Personal dotfile repo
# Author: Blake Jakopovic
# Git:    https://github.com/blakejakopovic/dotfiles

[ -z "$DOTFILES_DIR" ] && { echo "Error: ${0} cannot be called directly"; exit 1; }

DOTFILES_DIR="${DOTFILES_DIR}/osx"

echo "==> Installing osx dotfiles..."

r_symlink .git-credentials