#!/usr/bin/env bash
#
# ~/.dotfiles/linux/install
# dotfiles -- Personal dotfile repo
# Author: Blake Jakopovic
# Git:    https://github.com/blakejakopovic/dotfiles

[ -z "$DOTFILES_DIR" ] && { echo "Error: ${0} cannot be called directly"; exit 1; }

DOTFILES_DIR="${DOTFILES_DIR}/linux"

echo "==> Installing linux dotfiles..."

# Ensure required paths
r_dir .config/i3
r_dir .config/sway
r_dir .config/termite

# Symlink config files
r_symlink .config/i3/config i3.conf
r_symlink .config/sway/config sway.conf
r_symlink .config/termite/config termite.conf

# Symlink dotfiles
r_symlink .compton.conf
r_symlink .i3status.conf
r_symlink .xbindkeysrc
r_symlink .xinitrc
r_symlink .Xresources