#!/usr/bin/env bash
#
# ~/.dotfiles/redhat/install

[ -z "$DOTFILESPATH" ] && { echo "Error: ${0} cannot be called directly"; exit 1; }

DOTFILESPATH="${DOTFILESPATH}/redhat"

echo "==> Installing Red Hat dotfiles..."

echo "${PADDING}[none]"
