#!/usr/bin/env bash
#
# ~/.dotfiles/redhat/install

[ -z "$DOTFILES_DIR" ] && { echo "Error: ${0} cannot be called directly"; exit 1; }

DOTFILES_DIR="${DOTFILES_DIR}/redhat"

echo "==> Installing Red Hat dotfiles..."

echo "${PADDING}[none]"
